<?php
PARALLEL_REGIONS:100
PARALLEL_ANNOTATIONS:8
PARALLEL_BLAST_PROCESS:4
USER_MODE:restricted
BLAST:/var/www/genotate.life/services/blast/bin/makeblastdb
BLASTDB:/var/www/genotate.life/workspace/blastdb
DATABASE_CONFIG:/var/www/genotate.life/workspace/config/database.config
DIR_BINARIES:/var/www/genotate.life/binaries
DIR_DATABASE_CONFIG:/var/www/genotate.life/workspace/config
DIR_SERVICES:/var/www/genotate.life/services
DIR_STORAGE:/var/www/genotate.life/workspace/storage
DIR_TMP:/var/www/genotate.life/tmp
DIR_WORKSPACE:/var/www/genotate.life/workspace
GENOTATE:/var/www/genotate.life/binaries/genotate.jar
GENOTATE_CONFIG:/var/www/genotate.life/binaries/genotate.config
JAVA:/var/www/genotate.life/services/javajdk/bin/java
?>